### ISSUE TITLE
step_resource/step_resource_service_stop_do_stuff_start.rst vs. step_resource/step_resource_mount_mysql.rst

### ISSUE THREAD

**Issue by d-higuchi** [chef-boneyard/chef-web-docs-2016#131]
step_resource/step_resource_service_stop_do_stuff_start.rst and step_resource/step_resource_mount_mysql.rst have almost same content (the latter maybe have typo).

BTW, chef_master/source/resource_service.rst, chef_master/source/resource_execute.rst and chef_master/source/resource_mount.rst include both step_resource/step_resource_service_stop_do_stuff_start.rst and step_resource/step_resource_mount_mysql.rst.

So, step_resource/step_resource_mount_mysql.rst is just redundant or need to update?

**Comment by jamescott** [comment]
Ah. Good catch.

The redundancy in the examples (across the resources) is intended (because I want to have some resource usage examples that show using multiple resources to achieve a goal), but the redundancy in the steps_ topics is not intended. I deleted the mysql example and updated all of the resource topics to reflect the single example.

https://github.com/opscode/chef-docs/commit/ebedb72566e548890ee9160792af0c02939f5ec8

**Comment by d-higuchi** [comment]
I see your intention. Thank you for your work.
