### ISSUE TITLE
Need to open port 10003 on back end servers in HA Enterprise Chef install of Push Jobs

### ISSUE THREAD

**Issue by micgo** [chef-boneyard/chef-web-docs-2016#218]
When installing Push Jobs into a HA Enterprise Chef environment, port 10003 needs to be open on both back ends to the front end servers for the API calls to be passed through.

This isn't documented anywhere at the moment, but should probably go along with the documentation here: [Install Push Jobs](http://docs.opscode.com/install_push_jobs.html)

**Comment by jamescott** [comment]
http://docs.opscode.com/push_jobs.html#requirements

There is a bullet that mentions ports 10000-10003. Should that be updated to be more clear? Also, I should add the push job ports to the other docs that mention ports. Like this one: http://docs.opscode.com/server_firewalls_and_ports.html.

For the Install topic, adding a step at #3(?) that says "Ensure that port 10003 is open so that the Push Jobs client may communicate with the Push Jobs server."

**Comment by jamescott** [comment]
https://github.com/opscode/chef-docs/commit/1a2f6eb9d18b8ebc25753c3a2bbdb5c7b6478d0f

**Comment by micgo** [comment]
Yeah, I think after talking with @charlesjohnson that this should really just be adding the opening of ports 10000-10003 to all back ends for to the Install Push Jobs page. It looks like 10003 won't be sufficient by itself. I don't think we need to open those ports on the Front Ends though.

**Comment by jamescott** [comment]
Updated to clarify for back end, ports 10000-10003 must be open.

**Comment by charlesjohnson** [comment]
I didn't realize the pushy daemons ran on back-end hosts in the HA config, I thought they ran on front-end.
