### ISSUE TITLE
OSS chef server 11 on debian

### ISSUE THREAD

**Issue by pierreozoux** [chef-boneyard/chef-web-docs-2016#72]
Hi,

I did this [little tutorial](https://coderwall.com/p/u6j6mq?i=1&p=1&q=author%3Apierre-o&t%5B%5D=pierre-o) to install OSS chef server 11 on debian. It's a bit hacky but it's working, if you are interested, I can write a documentation page here :)

Let me know!

**Comment by ghost** [comment]
Pierre, please!

**Comment by pierreozoux** [comment]
Hi, I though it was working, but  after some weeks, realised, that it was not stable.. That's why the link is dead. I should close the issue then.

But if you want to investigate, the idea was just to add some packages from unstable.

**Comment by pierreozoux** [comment]
I found these notes, if you are interested :

How to install chef11 on your debian server, and configure your workstation to work with it!

On your chef server as root:

``` bash
#Add experimental to your debian repo
apt-get update 
apt-get upgrade
echo "deb http://ftp.debian.org/debian experimental main" >> /etc/apt/sources.list
apt-get update

#Install necessary library
apt-get -t experimental install libc6

#Install chef-server
wget https://opscode-omnibus-packages.s3.amazonaws.com/ubuntu/12.04/x86_64/chef-server_11.0.8-1.ubuntu.12.04_amd64.deb
 dpkg -i chef-server_11.0.8-1.ubuntu.12.04_amd64.deb
 chef-server-ctl reconfigure
 chef-server-ctl test
```

On your workstation :

``` bash
#Copy the necessary keys from the chef-server
mkdir ~/.chef
scp root@chef-server:/etc/chef-server/admin.pem ~./chef/admin.pem
scp root@chef-server:/etc/chef-server/chef-validator.pem ~./chef/validation.pem

#Create your knife configuration
knife configure --initial
Overwrite /Users/PierreOzoux/.chef/knife.rb? (Y/N) Y
Please enter the chef server URL: [http://Pierres-iMac.local:4000] https://chef.lisbon
Please enter a name for the new user: [PierreOzoux] pierre
Please enter the existing admin name: [admin]
Please enter the location of the existing admin's private key: [/etc/chef/admin.pem] ~/.chef/admin.pem
Please enter the validation clientname: [chef-validator]
Please enter the location of the validation key: [/etc/chef/validation.pem] ~/.chef/validation.pem
Please enter the path to a chef repository (or leave blank): ~/chef
Creating initial API user...
Please enter a password for the new user:
Created user[pierre]
Configuration file written to /Users/PierreOzoux/.chef/knife.rb
```

source :
http://www.opscode.com/blog/2013/03/11/chef-11-server-up-and-running/
http://docs.opscode.com/install_server.html

**Comment by ghost** [comment]
Thanks for reply!
In debian 6, I must use `chef-server_11.0.8-1.ubuntu.11.04_amd64.deb` (`chef-server_11.0.8-1.ubuntu.12.04_amd64.deb` causes GLIBC-related errors).
Next problem - `chef-server-ctl reconfigure` fails starting rabbitmq server.

<pre>
================================================================================
Error executing action `run` on resource 'execute[/opt/chef-server/embedded/bin/chpst -u chef_server -U chef_server /opt/chef-server/embedded/bin/rabbitmqctl wait /var/opt/chef-server/rabbitmq/db/rabbit@localhost.pid]'
================================================================================
Mixlib::ShellOut::ShellCommandFailed
------------------------------------
Expected process to exit with [0], but received '2'
---- Begin output of /opt/chef-server/embedded/bin/chpst -u chef_server -U chef_server /opt/chef-server/embedded/bin/rabbitmqctl wait /var/opt/chef-server/rabbitmq/db/rabbit@localhost.pid ----
STDOUT: Waiting for rabbit@localhost ...
pid is 9978 ...
STDERR: Error: process_not_running
---- End output of /opt/chef-server/embedded/bin/chpst -u chef_server -U chef_server /opt/chef-server/embedded/bin/rabbitmqctl wait /var/opt/chef-server/rabbitmq/db/rabbit@localhost.pid ----
</pre>

I think this problem caused by already running rabbitmq on this machine.

**Comment by mrjcleaver** [comment]
Is there a reason Chef 11 on Debian is not officially supported? My O/S team are complaining that Ubuntu Server TLS is "pretty weak" for a Server OS, and - especially - there are problems with Ubuntu's Network Manager being overly controlling.

Sorry if this is not the best place for the question - let me know & I will re-post it.

Thanks, M.

**Comment by jespada** [comment]
On Debian 7 you can install chef-server_11.0.8-1.ubuntu.11.04_amd64.deb without any problems, if you try the package for ubuntu versions > 11.04 you gonna have dependencies problems (see glibc version)

**Comment by mrjcleaver** [comment]
Thanks Jorge!

**Comment by midorinet** [comment]
Hi,

I'm trying to setup Chef Server on Debian Wheezy, however I'm stuck on ruby_block[supervise_rabbitmq_sleep] action run

Any idea how to fix it? Note : I'm using chef-server_11.1.1-1_amd64.deb
