### ISSUE TITLE
opscode-solr4 tuning info needs review

### ISSUE THREAD

**Issue by jblaine** [chef-boneyard/chef-web-docs-2016#752]
https://docs.chef.io/server_tuning.html#opscode-solr4 says:

> Suggested value: 256 per every 25 nodes. For example, an organization with
> 300 nodes, this value should be set to 3072.

For 1300 nodes, that results in a setting of 13312. @jeremiahsnapp reports that all of Hosted Chef uses a value of only 8192.

As more research that the above info is bad, @irvingpop 's blog at https://irvingpop.github.io/blog/2015/04/20/tuning-the-chef-server-for-scale/ says:

> Solr JVM tuning: By default we compute Solr’s JVM heap size
> to be either 25% of system memory or 1024MB, whichever is
> smaller. Large chef server clusters should increase this value to
> smaller of 25% of system memory or 4096MB.
> 
> WARNING: It is not recommended to use a JVM heap_size above 8GB, at
> that level the cost of Garbage Collection becomes too high and impacts
> performance worse than using a smaller heap

**Comment by irvingpop** [comment]
Great point @jblaine

In our experience Solr functions well in the range of 1GB-8GB (how much heap you need depends heavily on query load and index size and is best answered with JVM monitoring).   Below 1GB, you're likely to see OOMs even for simple things (like the reindex of any moderate sized org).   Above 8GB and the cost of garbage collection starts getting bad.

The benefit of using more than 8GB is also questionable: The largest Chef clusters we've ever encountered (hosted chef and some customer clusters) have performed fine with an 8GB heap (particularly since we upgraded to Solr 4).

**Comment by irvingpop** [comment]
cc: @jamescott

**Comment by jamescott** [comment]
The section that references the tuning guidance for the `opscode_solr4['heap_size']` setting is updated.

**Comment by jblaine** [comment]
Uncoordinated and hand-missing hi5
