### ISSUE TITLE
Lacking documentation for writing own Providers

### ISSUE THREAD

**Issue by d-higuchi** [chef-boneyard/chef-web-docs-2016#76]
Docs does not have a documentation for writing own Providers.
For example, new_resource, current_reource, load_current_resource,
updated_by_last_action, whyrun_supported, converge_by...
They are needed to write proper Providers.
Would you provide their documentation and some examples?

**Comment by jamescott** [comment]
This is at the top of my queue, actually. I am hoping to have a draft out there sometime later next week for the whole "Custom LWRP" set of topics.

**Comment by jamescott** [comment]
So take a look at this: http://docs.opscode.com/lwrp_custom_provider.html

If you have additional thoughts about what is in there, please let me know. Incidentally, there are "two types" of lightweight providers -- one of them is built around core Chef resource and the other is built using primarily custom Ruby code. It is the latter which requires the converge_by blocks (to enable the whyrun messaging). The former, because whyrun is already built into the core Chef resources, does not require the converge_by method.

This topic: http://docs.opscode.com/lwrp_custom_provider_ruby.html ... I am still working on, but there is a description of the converge_by method in there.

Because LWRPs are so flexible with regard to the approach one might take when building them, looking at what other people have done can be quite helpful too. Some great non-Opscode examples of LWRPs can be found here:

https://github.com/RiotGames/rbenv-cookbook

and:

https://github.com/fnichol/chef-rvm/blob/master/providers/gemset.rb (just one of many in that collection of provider files)

Hope this helps,

James

**Comment by d-higuchi** [comment]
Thank you for your great works!
